version: "3.5"

services:
  db:
    image: postgres:16-alpine
    container_name: "${DOCKER_PG_CONTAINER_NAME}"
    volumes:
      - "${DOCKER_PG_VOLUME}:/var/lib/postgresql/data/"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "${DOCKER_PG_USER}"
      POSTGRES_PASSWORD: "${DOCKER_PG_PASSWORD}"
      POSTGRES_DB: "${DOCKER_PG_DB}"
    restart: always
  app:
    build:
        context: .
        dockerfile:  "./docker/app/Dockerfile"
    container_name: "${DOCKER_APP_CONTAINER_NAME}"
    environment:
      APP_BROKER_URI: "${APP_BROKER_URI}"
      DOCKER_PG_USER: "${DOCKER_PG_USER}"
      DOCKER_PG_PASSWORD: "${DOCKER_PG_PASSWORD}"
      DOCKER_PG_DB: "${DOCKER_PG_DB}"
      DOCKER_PG_URI: "${DOCKER_PG_CONTAINER_NAME}"
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"

networks:
  default:
    driver: bridge
    name: "${DOCKER_NETWORK}"
